- name: Install keepalived
  hosts: all

  tasks:
    - name: Install keepalived
      ansible.builtin.apt:
        name: keepalived
        state: latest
        update_cache: true
      become: true
