- name: Install Docker
  hosts:
    - proxmox_ubuntu
    - ubuntu
  become: true

  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Install required system packages
      ansible.builtin.apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: present
        update_cache: true

    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    # this step is to prevent needing to use sudo when running docker commands
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ lookup('env', 'USER') }}"
        groups: docker
        append: true

    # this step enables the docker api so that we can manage multiple hosts in a single instance of portainer
    - name: Enable Docker API
      ansible.builtin.replace:
        path: /lib/systemd/system/docker.service
        regexp: '^ExecStart=\/usr\/bin\/dockerd(?!.*-H=tcp:\/\/0\.0\.0\.0:2375.*)'
        replace: 'ExecStart=/usr/bin/dockerd -H=tcp://0.0.0.0:2375'
        backup: true

    # the following steps install docker compose
    - name: Create CLI plugins directory
      become: false
      ansible.builtin.file:
        path: ~/.docker/cli-plugins
        state: directory
        mode: 0777

    - name: Download docker compose and validate checksum (sha256)
      become: false
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64
        dest: ~/.docker/cli-plugins/docker-compose
        checksum: sha256:https://github.com/docker/compose/releases/download/v2.16.0/docker-compose-linux-x86_64.sha256
        mode: u+x
